# Generated by Django 4.1.5 on 2023-02-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harbor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harbor',
            old_name='place',
            new_name='sea',
        ),
    ]
