# Generated by Django 4.1.5 on 2023-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harbor', '0003_rename_address1_harbor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harbor',
            name='sea',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
