# Generated by Django 4.1.5 on 2023-02-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harbor', '0004_alter_harbor_sea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harbor',
            name='sea',
        ),
    ]
