# Generated by Django 4.1.5 on 2023-02-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harbor", "0006_harbor_sea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harbor",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
