# Generated by Django 4.1.5 on 2023-02-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harbor", "0007_alter_harbor_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="harbor",
            name="sea",
        ),
    ]
