# Generated by Django 4.1.5 on 2023-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harbor", "0009_harbor_sea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harbor",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
