# Generated by Django 4.1.5 on 2023-04-12 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fishing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("harbor", "0010_alter_harbor_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fishing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_business_name", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("reason_for_deletion", models.CharField(max_length=255, null=True)),
                ("needs_check", models.BooleanField(default=True)),
                ("business_address", models.CharField(max_length=255)),
                ("site_url", models.CharField(max_length=255, null=True)),
                (
                    "thumbnail",
                    models.ImageField(null=True, upload_to=fishing.models.upload_to),
                ),
                ("introduce", models.TextField(null=True)),
                ("maximum_seat", models.PositiveIntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fishing",
            },
        ),
        migrations.CreateModel(
            name="FishingCrawler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer", models.CharField(max_length=255)),
                ("uid", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "fishing_crawler",
            },
        ),
        migrations.CreateModel(
            name="FishingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "fishing_group",
            },
        ),
        migrations.CreateModel(
            name="FishingSpeciesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "fishing_species_item",
            },
        ),
        migrations.CreateModel(
            name="FishingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "fishing_type",
            },
        ),
        migrations.CreateModel(
            name="FishingSpeciesMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=255)),
                ("maximum_seat", models.PositiveIntegerField()),
                (
                    "fishing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing.fishing",
                    ),
                ),
                (
                    "fishing_species_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing.fishingspeciesitem",
                    ),
                ),
            ],
            options={
                "db_table": "fishing_species_month",
            },
        ),
        migrations.CreateModel(
            name="FishingBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("person", models.PositiveIntegerField(default=1)),
                (
                    "fishing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing.fishing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fishing_booking",
            },
        ),
        migrations.AddField(
            model_name="fishing",
            name="fishing_crawler",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fishing.fishingcrawler",
            ),
        ),
        migrations.AddField(
            model_name="fishing",
            name="fishing_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fishing.fishinggroup",
            ),
        ),
        migrations.AddField(
            model_name="fishing",
            name="fishing_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fishing.fishingtype"
            ),
        ),
        migrations.AddField(
            model_name="fishing",
            name="harbor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="harbor.harbor"
            ),
        ),
    ]
