# Generated by Django 4.1.5 on 2023-04-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0002_fishingmonth_fishingspecies_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FishingSpecies",
        ),
    ]
