# Generated by Django 4.1.5 on 2023-02-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_alter_fishingitem_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FishingItem',
        ),
    ]
