# Generated by Django 4.1.5 on 2023-04-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0003_delete_fishingspecies"),
    ]

    operations = [
        migrations.CreateModel(
            name="FishingSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fishing_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing.fishingmonth",
                    ),
                ),
                (
                    "fishing_species_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing.fishingspeciesitem",
                    ),
                ),
            ],
            options={
                "db_table": "fishing_species",
            },
        ),
    ]
