# Generated by Django 4.1.5 on 2023-02-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishingitem',
            old_name='admit',
            new_name='price',
        ),
        migrations.AddField(
            model_name='fishingitem',
            name='seat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
