# Generated by Django 4.1.5 on 2023-02-07 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harbor', '0001_initial'),
        ('fishing', '0005_rename_admit_fishingitem_price_fishingitem_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=255, null=True)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('introduce', models.CharField(max_length=255, null=True)),
                ('seat', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'fishing',
            },
        ),
        migrations.CreateModel(
            name='FishingSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fishing_species',
            },
        ),
        migrations.CreateModel(
            name='FishingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fishing_type',
            },
        ),
        migrations.DeleteModel(
            name='FishingItem',
        ),
        migrations.AddField(
            model_name='fishing',
            name='fish_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fishingspecies'),
        ),
        migrations.AddField(
            model_name='fishing',
            name='fishing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fishingtype'),
        ),
        migrations.AddField(
            model_name='fishing',
            name='harbor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harbor.harbor'),
        ),
    ]
