# Generated by Django 4.1.5 on 2023-02-07 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishing', '0006_fishing_fishingspecies_fishingtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remaining_seat', models.CharField(max_length=255, null=True)),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fishing')),
            ],
            options={
                'db_table': 'fishing_seat',
            },
        ),
        migrations.CreateModel(
            name='FishingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_person', models.CharField(max_length=255, null=True)),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fishing')),
                ('fishing_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.fishingschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fishing_booking',
            },
        ),
    ]
