# Generated by Django 4.1.5 on 2023-02-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0007_fishingschedule_fishingbooking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fishingschedule',
            table='fishing_schedule',
        ),
    ]
