# Generated by Django 4.1.5 on 2023-02-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0009_remove_fishingbooking_fishing_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishingbooking',
            name='date',
        ),
    ]
