# Generated by Django 4.1.5 on 2023-02-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0010_remove_fishingbooking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingbooking',
            name='date',
            field=models.DateField(default=20220101),
            preserve_default=False,
        ),
    ]
