# Generated by Django 4.1.5 on 2023-02-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0012_remove_fishingbooking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingSpeciesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fishing_species_item',
            },
        ),
        migrations.RemoveField(
            model_name='fishing',
            name='fish_species',
        ),
        migrations.RemoveField(
            model_name='fishingspecies',
            name='name',
        ),
        migrations.AddField(
            model_name='fishingbooking',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishingspecies',
            name='fishing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fishing.fishing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishingspecies',
            name='fishing_species_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fishing.fishingspeciesitem'),
            preserve_default=False,
        ),
    ]
