# Generated by Django 4.1.5 on 2023-02-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0013_fishingspeciesitem_remove_fishing_fish_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishingbooking',
            name='fishing',
        ),
        migrations.RemoveField(
            model_name='fishingbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fishingspecies',
            name='fishing',
        ),
        migrations.RemoveField(
            model_name='fishingspecies',
            name='fishing_species_item',
        ),
        migrations.DeleteModel(
            name='Fishing',
        ),
        migrations.DeleteModel(
            name='FishingBooking',
        ),
        migrations.DeleteModel(
            name='FishingSpecies',
        ),
        migrations.DeleteModel(
            name='FishingSpeciesItem',
        ),
        migrations.DeleteModel(
            name='FishingType',
        ),
    ]
