# Generated by Django 4.1.5 on 2023-02-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0015_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishing',
            old_name='name',
            new_name='business_name',
        ),
    ]
