# Generated by Django 4.1.5 on 2023-02-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0017_fishing_business_address_fishing_referrer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fishing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fishing",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
