# Generated by Django 4.1.5 on 2023-02-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0018_fishing_created_at_fishing_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishing",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fishing",
            name="updated_at",
        ),
    ]
