# Generated by Django 4.1.5 on 2023-02-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0020_fishing_created_at_fishing_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="species",
            field=models.ManyToManyField(
                blank=True,
                related_name="fishing_species_set",
                through="fishing.FishingSpecies",
                to="fishing.fishingspeciesitem",
            ),
        ),
    ]
