# Generated by Django 4.1.5 on 2023-02-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0021_fishing_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
