# Generated by Django 4.1.5 on 2023-02-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0022_alter_fishing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
