# Generated by Django 4.1.5 on 2023-02-13 19:27

from django.db import migrations, models
import fishing.models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0023_alter_fishing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="thumbnail",
            field=models.FileField(default=1, upload_to=fishing.models.upload_to),
            preserve_default=False,
        ),
    ]
