# Generated by Django 4.1.5 on 2023-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0026_alter_fishing_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="site_url",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
