# Generated by Django 4.1.5 on 2023-02-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0027_alter_fishing_site_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="species",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="fishing_species_set",
                through="fishing.FishingSpecies",
                to="fishing.fishingspeciesitem",
            ),
        ),
    ]
