# Generated by Django 4.1.5 on 2023-02-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0028_alter_fishing_species"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="species",
            field=models.ManyToManyField(
                blank=True,
                related_name="fishing_species_set",
                through="fishing.FishingSpecies",
                to="fishing.fishingspeciesitem",
            ),
        ),
        migrations.AlterField(
            model_name="fishingspecies",
            name="fishing_species_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fishing.fishingspeciesitem",
            ),
        ),
    ]
