# Generated by Django 4.1.5 on 2023-02-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0029_alter_fishing_species_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="crawled_business_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
