# Generated by Django 4.1.5 on 2023-02-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0030_fishing_crawled_business_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="is_changed_crawled_business_name",
            field=models.BooleanField(default=False),
        ),
    ]
