# Generated by Django 4.1.5 on 2023-02-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0031_fishing_is_changed_crawled_business_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="order_of_buttons",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
