# Generated by Django 4.1.5 on 2023-02-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0032_fishing_order_of_buttons"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="crawler_business_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
