# Generated by Django 4.1.5 on 2023-02-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0033_fishing_crawler_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="crawler_business_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
