# Generated by Django 4.1.5 on 2023-02-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0034_alter_fishing_crawler_business_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fishing",
            old_name="business_name",
            new_name="display_business_name",
        ),
    ]
