# Generated by Django 4.1.5 on 2023-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0035_rename_business_name_fishing_display_business_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="crawled_business_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
