# Generated by Django 4.1.5 on 2023-02-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0037_alter_fishing_crawled_business_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fishing",
            old_name="is_changed_crawled_business_name",
            new_name="is_display",
        ),
    ]
