# Generated by Django 4.1.5 on 2023-02-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0039_remove_fishing_is_display_fishing_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="FishingCrawler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referrer", models.CharField(max_length=255)),
                ("uid", models.CharField(max_length=255)),
                ("crawler_business_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "fishing_crawler",
            },
        ),
        migrations.RemoveField(
            model_name="fishing",
            name="crawled_business_name",
        ),
        migrations.RemoveField(
            model_name="fishing",
            name="crawler_business_name",
        ),
        migrations.RemoveField(
            model_name="fishing",
            name="order_of_buttons",
        ),
        migrations.AddField(
            model_name="fishing",
            name="fishing_crawler",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fishing.fishingcrawler",
            ),
            preserve_default=False,
        ),
    ]
