# Generated by Django 4.1.5 on 2023-02-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0041_fishinggroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishing",
            name="fishing_crawler",
        ),
    ]
