# Generated by Django 4.1.5 on 2023-02-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0044_fishing_crawler_business_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishing",
            name="crawler_business_name",
        ),
    ]
