# Generated by Django 4.1.5 on 2023-02-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0045_remove_fishing_crawler_business_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishing",
            name="fishing_group",
        ),
    ]
