# Generated by Django 4.1.5 on 2023-02-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0046_remove_fishing_fishing_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="fishing_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fishing.fishinggroup",
            ),
        ),
    ]
