# Generated by Django 4.1.5 on 2023-02-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0049_fishinggroup_fishing_fishing_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="introduce",
            field=models.TextField(null=True),
        ),
    ]
