# Generated by Django 4.1.5 on 2023-02-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0050_alter_fishing_introduce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
