# Generated by Django 4.1.5 on 2023-02-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0053_alter_fishing_fishing_crawler_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="fishing_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fishing.fishinggroup",
                unique=True,
            ),
        ),
    ]
