# Generated by Django 4.1.5 on 2023-02-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0055_alter_fishing_fishing_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishing",
            name="referrer",
        ),
    ]
