# Generated by Django 4.1.5 on 2023-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0056_remove_fishing_referrer"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="needs_check",
            field=models.BooleanField(default=False),
        ),
    ]
