# Generated by Django 4.1.5 on 2023-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0057_fishing_needs_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="seat",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
