# Generated by Django 4.1.5 on 2023-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0058_alter_fishing_seat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishingbooking",
            name="additional_person",
        ),
        migrations.AddField(
            model_name="fishingbooking",
            name="person",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
