# Generated by Django 4.1.5 on 2023-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0059_remove_fishingbooking_additional_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="needs_check",
            field=models.BooleanField(default=True),
        ),
    ]
