# Generated by Django 4.1.5 on 2023-04-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0060_alter_fishing_needs_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishing",
            name="reason_for_deletion",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
