# Generated by Django 4.1.5 on 2023-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0061_fishing_reason_for_deletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishing",
            name="reason_for_deletion",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
