# Generated by Django 4.1.5 on 2023-04-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0062_alter_fishing_reason_for_deletion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishing",
            name="species",
        ),
    ]
