# Generated by Django 4.1.5 on 2023-04-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0064_fishing_species"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishing",
            name="species",
        ),
    ]
