# Generated by Django 4.1.5 on 2023-04-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0065_remove_fishing_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishingspecies",
            name="date",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
