# Generated by Django 4.1.5 on 2023-04-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0066_fishingspecies_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishingspecies",
            name="month",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
