# Generated by Django 4.1.5 on 2023-04-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0067_fishingspecies_month"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishingspecies",
            name="date",
        ),
    ]
