# Generated by Django 4.1.5 on 2023-04-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0068_remove_fishingspecies_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FishingSpecies",
            new_name="FishingSpeciesMonth",
        ),
        migrations.AlterModelTable(
            name="fishingspeciesmonth",
            table="fishing_species_month",
        ),
    ]
