# Generated by Django 4.1.5 on 2023-04-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0069_rename_fishingspecies_fishingspeciesmonth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishingspeciesmonth",
            name="month",
            field=models.DateTimeField(),
        ),
    ]
