# Generated by Django 4.1.5 on 2023-04-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0070_alter_fishingspeciesmonth_month"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fishing",
            old_name="seat",
            new_name="maximum_seat",
        ),
        migrations.AddField(
            model_name="fishingspeciesmonth",
            name="maximum_seat",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
