# Generated by Django 4.1.5 on 2023-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0071_rename_seat_fishing_maximum_seat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishingspeciesmonth",
            name="month",
            field=models.DateField(),
        ),
    ]
