# Generated by Django 4.1.5 on 2023-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing", "0072_alter_fishingspeciesmonth_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishingspeciesmonth",
            name="month",
            field=models.CharField(max_length=255),
        ),
    ]
