# Generated by Django 4.1.5 on 2023-03-30 13:48

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", account.models.CustomUserManager()),
            ],
        ),
    ]
